services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/sj-seed/ai:latest
    env_file:
      - .env
    ports:
      - '8000:8000'
    init: true
    restart: unless-stopped
